---

    - name: Run yum update
      yum:
        name: '*'
        state: latest
        
    - name: Install EPEL-Release
      yum:
        name: epel-release
        state: latest

    - name: Install OpenVPN
      yum:
        name: openvpn
        state: latest
      register: openvpn_install

    - name: Install easy-rsa
      yum:
        name: easy-rsa
        state: latest

    - name: Install RSync
      yum:
        name: rsync
        state: latest

    - name: Add OpenVPN server config
      template:
        src: server.conf
        dest: /etc/openvpn/server.conf
      when: openvpn_install is changed

    - name: Create a directory keys
      file:
        path: /etc/openvpn/easy-rsa/keys
        state: directory
        mode: '0755'

    - name: Copy a easy-rsa directory
      copy:
        src: /usr/share/easy-rsa/3/
        dest: /etc/openvpn/easy-rsa
        mode: preserve
      when: openvpn_install is changed

    - name: Copy a vars
      copy:
        src: vars
        dest: /etc/openvpn/easy-rsa/vars
      when: openvpn_install is changed

    - name: Copy an openssl.cnf
      copy:
        src: /usr/share/easy-rsa/3/openssl-easyrsa.cnf
        dest: /etc/openvpn/easy-rsa/openssl.cnf
      when: openvpn_install is changed

    - name: Genarated keys and certs
      shell:
        cmd: |
          source ./vars
          ./easyrsa init-pki
          ./easyrsa build-ca nopass
          ./easyrsa gen-req server nopass
          ./easyrsa sign-req server server
          openssl verify -CAfile pki/ca.crt pki/issued/server.crt
          ./easyrsa gen-req client nopass
          ./easyrsa sign-req client client
          openssl verify -CAfile pki/ca.crt pki/issued/client.crt
          ./easyrsa gen-dh
        chdir: /etc/openvpn/easy-rsa
      when: openvpn_install is changed

    - name: Create a directory for OpenVPN keys
      file:
        path: /etc/openvpn/keys
        state: directory
        mode: '0755'
      when: openvpn_install is changed

    - name: Copy an ca.crt
      copy:
        src: /etc/openvpn/easy-rsa/pki/ca.crt
        dest: /etc/openvpn/server/ca.crt
        mode: preserve
      when: openvpn_install is changed

    - name: Copy an dh.pem
      copy:
        src: /etc/openvpn/easy-rsa/pki/dh.pem
        dest: /etc/openvpn/server/dh2048.pem
        mode: preserve
      when: openvpn_install is changed

    - name: Copy a server.key
      copy:
        src: /etc/openvpn/easy-rsa/pki/private/server.key
        dest: /etc/openvpn/server/server.key
        mode: preserve
      when: openvpn_install is changed

    - name: Copy a server.crt
      copy:
        src: /etc/openvpn/easy-rsa/pki/issued/server.crt
        dest: /etc/openvpn/server/server.crt
        mode: preserve
      when: openvpn_install is changed

    - name: Copy a client.crt
      copy:
        src: /etc/openvpn/easy-rsa/pki/issued/client.crt
        dest: /etc/openvpn/client/client.crt
        mode: preserve
      when: openvpn_install is changed

    - name: Copy a client.key
      copy:
        src: /etc/openvpn/easy-rsa/pki/private/client.key
        dest: /etc/openvpn/client/client.key
        mode: preserve
      when: openvpn_install is changed

    - name: Save ca.crt to variable
      shell: cat /etc/openvpn/server/ca.crt
      register: cat_ca_crt
      when: openvpn_install is changed

    - name: Save client.crt to variable
      shell: cat /etc/openvpn/client/client.crt | sed -n '/BEGIN\ CERTIFICATE/,$p'
      register: cat_client_crt
      when: openvpn_install is changed

    - name: Save client.key to variable
      shell: cat /etc/openvpn/client/client.key
      register: cat_client_key
      when: openvpn_install is changed

    - name: Add OpenVPN client config
      template:
        src: client.conf
        dest: /etc/openvpn/client.conf
      when: openvpn_install is changed

    - firewalld:
        port: 1194/udp
        permanent: yes
        state: enabled

    - firewalld:
        source: 10.8.0.0/24
        permanent: yes
        state: enabled

    - name: Reload Firewalld service
      service:
        name: firewalld
        state: reloaded
        enabled: yes

    - name: Start OpenVPN service
      service:
        name: openvpn@server
        state: started
        enabled: yes
